unbind r

bind r source-file ~/.tmux.conf

set -g prefix C-a

set -g mouse on

# toggle panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# resize panes
bind-key H resize-pane -L 5
bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key L resize-pane -R 5

bind-key | split-window -h
bind-key - split-window -v

bind-key m resize-pane -Z 10

bind-key f run-shell "tmux new-window -n tmuxs 'tmuxs'" 

set-option -g status-position bottom

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'rose-pine/tmux'

set -g @plugin 'tmux-plugins/tpm'

set -g @rose_pine_variant 'moon' # Options are 'main', 'moon' or 'dawn'


run '~/.tmux/plugins/tpm/tpm'

set -g status-style bg=default,fg=default
set -g window-style bg=default,fg=default
set -g pane-border-style bg=default,fg=default
set -g pane-active-border-style bg=default,fg=default
